### PR TITLE
Use URLBuilder instead of Url in mappers and HttpFetcher

### PR DESCRIPTION
**Pull request by ayanyev**
There is an issue when full resource url is split between httpClient config and asyncPainterResource call:
```
defaultRequest {
     url("https://kamel.media")
}
asyncPainterResource("/image.jpg")
```
If mapper and fetcher use Url respectively as output and input data, the resulting resource url will look like:
`https://localhost:80/image.jpg`

This happens due to `DefaultRequest.mergeUrls(...)` implementation. 

DefaultRequestConfigTest is added.

### CODE REVIEW

**Comment by luca992** [comment]
Does `fun URLBuilder.takeFrom(url: Url): URLBuilder` not work?

**Comment by ayanyev** [comment]
The problem is when mapper maps to Url, localhost:80 added to `/image.jpg` with applyOrigin().
```
    public fun build(): Url {
        **applyOrigin()**
        return Url(
            protocol = protocol,
            host = host,
```
When it comes to DefaultRequest.mergeUrls(), execution is stopped at the very beginning because host is not empty.
```
        private fun mergeUrls(baseUrl: Url, requestUrl: URLBuilder) {
            if (requestUrl.protocol == URLProtocol.HTTP) {
                requestUrl.protocol = baseUrl.protocol
            }
            **if (requestUrl.host.isNotEmpty()) return**
```
It ends up fetching image from localhost.

**Comment by eskatos** [comment]
This might be related to the upstream ktor issues
* https://github.com/ktorio/ktor/issues/1903
* https://youtrack.jetbrains.com/issue/KTOR-360

**Review by luca992 — CHANGES_REQUESTED** [review]
@ayanyev finally got to take a deeper look at this. I think you're right about using `UrlBuilder`.... I don't think it's a great idea to fully remove support from ktor Urls though. I think adding a `Url` to `UrlBuilder` mapper that's in the default kamel config would be a good idea.

@eskatos https://youtrack.jetbrains.com/issue/KTOR-360 looks like it's relevant. But, who knows when that will be implemented. Probably best to not wait for it

**Pull request closed without merging**
